### ISSUE TITLE
[Question] Auth config when using SAP API Business Hub

### ISSUE THREAD

**Issue by felihong** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#18]
Hi there 👋,

many thanks for the great work! 

When using [S/4HANA Cloud sandbox with APIKey](https://api.sap.com/api/API_BUSINESS_PARTNER/tryout), API keys are required instead of basic auth. How can I best integrate this in the current workload? 

Fyi I tried to patch `CostumHeaders` containing the APIkey in the script `src/api/src/business-partner/business-partner.service.ts` before executing the request, for example for getBusinessPartnerbyID:
```
  async getBusinessPartnerById (id: string): Promise<BusinessPartner> {
    return await businessPartnerApi
      .requestBuilder()
      .getByKey(id)
      .select(businessPartnerApi.schema.BUSINESS_PARTNER)
      .addCustomHeaders({ APIKey: '<MY-API-KEY>' })
      .execute({
        url: (process.env.ODATA_URL),
        username: (process.env.ODATA_USERNAME),
        password: (process.env.ODATA_USERPWD)
      })
  }
```

The header is attached in the request, but I still got 500 when testing locally. Do you have any ideas on this? 

Thank you!

**Comment by MartinPankraz** [comment]
dedicated guidance for APIKey handling added
