### ISSUE TITLE
[FEATURE] Add Azure AAD app registration for SAP Principal Propagation with Azure APIM

### ISSUE THREAD

**Issue by MartinPankraz** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#37]
### What area do you want to see improved?

- [X] app code
- [ ] documentation
- [X] infrastructure setup
- [ ] developer experience (GitHub CodeSpaces etc.)
- [X] other

### Is your feature request related to a problem? Please describe.

SAP Principal Propagation is essential for a production ready setup. A pre-configured  AAD app registration would pose a tremendous speed up in development causing less room for error.

### Describe the solution you'd like

Enable the "azd up" flow to reference an existing AAD app registration or create a new one and assign it to the app.

### Additional context

[inspirtation](https://github.com/Azure/reliable-web-app-pattern-dotnet/blob/main/infra/createAppRegistrations.sh)

**Comment by lechnerc77** [comment]
Link for reference: <https://github.com/Azure/reliable-web-app-pattern-dotnet/blob/main/infra/createAppRegistrations.sh>

**Comment by MartinPankraz** [comment]
implemented with committ #193b782 linked [here](https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart/commit/193b782839fc3dd37d8bf6c487b705539a80d356)

**Comment by MartinPankraz** [comment]
Optionally add capability to establish trust between app registration of the web app and the Azure APIM app registration.

**Comment by MartinPankraz** [comment]
Pending a nice flow chart to describe the app registration configuration flow supporting SAP Principal Propagation.

@lechnerc77 would appreciate a review on the bicep changes and scripting.

**Comment by lechnerc77** [comment]
@MartinPankraz Looks really good to me!

**Comment by MartinPankraz** [comment]
Implemented with committ [a00c4e065ff50f26f7dab2cd7bd9ae45c6e44ee9](https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart/commit/a00c4e065ff50f26f7dab2cd7bd9ae45c6e44ee9)
