### ISSUE TITLE
[FEATURE]: Add BTP deployment guide and structure

### ISSUE THREAD

**Issue by MartinPankraz** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#40]
### What area do you want to see improved?

documentation

### Is your feature request related to a problem? Please describe.

Deployment to BTP uses CF CLI. At least standard docs should be referenced to live up to the promise the app can run on both eco systems.

### Describe the solution you'd like

A similar deployment guide as for AZD or VSC extension

**Comment by lechnerc77** [comment]
Maybe as an addendum we can add the btp setup automator and provide a parameters and usecase file for the setup of the BTP account to make it ready for the deployment.

**Comment by lechnerc77** [comment]
Done with merge of PR #41
