### ISSUE TITLE
[FEATURE] Adjust project to azd 0.6.0-beta.2

### ISSUE THREAD

**Issue by lechnerc77** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#42]
### What area do you want to see improved?

documentation

### Is your feature request related to a problem? Please describe.

The new version of `azd` was released with several bug fixes that make some work arounds in the current setup obsolete.

The Login flow now works consistently for Azure accounts no matter if this is a personal or org account. This should be adjusted in the:

- code of the project
- documentation 

### Describe the solution you'd like

- Remove login flow workarounds pointing to AZ CLI (where possible)
- Adjust documentation accordingly

### Describe alternatives you've considered

There is none :-)

### Additional context

<https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_0.6.0-beta.1>

**Comment by lechnerc77** [comment]
I guess we can close that as the new version (0.7.0) will land this Wednesday. Anyway no compatibility adjustments needed for 0.6.0. As discussed hooks are out of scope for now

**Comment by MartinPankraz** [comment]
agreed
