### ISSUE TITLE
[FEATURE]: Upgrade to SAP Cloud SDK v3

### ISSUE THREAD

**Issue by MartinPankraz** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#46]
### What area do you want to see improved?

app code

### Is your feature request related to a problem? Please describe.

SAP Cloud SDK released v3 recently. Make sure breaking changes described [here](https://github.com/SAP/cloud-sdk-js/blob/main/V3-Upgrade-Guide.md) are taken care of. V2 has maintenance for security for 6 months.

Additional upgrade docs: https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-3

### Describe the solution you'd like

Whole project using SAP Cloud SDK v3

### Describe alternatives you've considered

None applicable

**Comment by MartinPankraz** [comment]
@lechnerc77  need to adjust the azd config in api.bicep, terraform, and btpsa to use node v18 due to the SDK v3 upgrade

**Comment by lechnerc77** [comment]
Didn't we have an issue with Node 18 and the App Service?
