### ISSUE TITLE
Compatibility] Adjust project for azd version 0.8.0

### ISSUE THREAD

**Issue by lechnerc77** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#58]
### What area do you want to see improved?

other

### Is your feature request related to a problem? Please describe.

`azd` version [0.8.0](https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_0.8.0-beta.1) was released and comes with some incompatible changes. The necessary adjustments must be made.

### Describe the solution you'd like

Adjust the project to be compatible with `azd` version 0.8.0 esp. when it comes to the alpha toggle for Terraform

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by MartinPankraz** [comment]
approved via #50
