### ISSUE TITLE
Updating/work-with this template for Azd Devcontainer feature.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart#81]
We are updating this template to support new features in `Azd Devcontainer`.

For the Azd Devcontainer feature: We will add the following code in `devcontainer.json` file,

``` 
"ghcr.io/azure/azure-dev/azd:latest": {}
``` 
And remove the relevant code for installing `azd` in `Dockerfile` under `.devcontainer` folder.
```
RUN curl -fsSL https://aka.ms/install-azd.sh | bash 
```

@rajeshkamal5050 , @MartinPankraz , @lechnerc77 for notification.

**Comment by lechnerc77** [comment]
I already created a PR on that (https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart/pull/72). However @MartinPankraz had to revert it as the pre-build of the Codespace failed.
